//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peplex_PFC.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peplex_PFC.UI.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Añadir.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Eliminar.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Editar.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ok.
        /// </summary>
        public static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///El archivo seleccionado no es un tipo de imagen válido.
        /// </summary>
        public static string ConfigControlImageNotValidError {
            get {
                return ResourceManager.GetString("ConfigControlImageNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione imagen de fondo.
        /// </summary>
        public static string ConfigControlSelectImageToBackground {
            get {
                return ResourceManager.GetString("ConfigControlSelectImageToBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccíone imagen para la carátula.
        /// </summary>
        public static string ConfigControlSelectImageToCover {
            get {
                return ResourceManager.GetString("ConfigControlSelectImageToCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Película actualizada con éxito..
        /// </summary>
        public static string ConfigFilmControlUpdateFilmSuccessfully {
            get {
                return ResourceManager.GetString("ConfigFilmControlUpdateFilmSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie actualizada con éxito..
        /// </summary>
        public static string ConfigFilmControlUpdateSerieSuccessfully {
            get {
                return ResourceManager.GetString("ConfigFilmControlUpdateSerieSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es incorrecta. No se actualizarán los datos del usuario..
        /// </summary>
        public static string ConfigUserControlCurrentPasswordError {
            get {
                return ResourceManager.GetString("ConfigUserControlCurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el usario con el que se ha iniciado sesión..
        /// </summary>
        public static string ConfigUserControlDelteUserError {
            get {
                return ResourceManager.GetString("ConfigUserControlDelteUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los dos campos para la contraseña deben estar rellenos si desea modificarla..
        /// </summary>
        public static string ConfigUserControlObligatoryBothPasswordField {
            get {
                return ResourceManager.GetString("ConfigUserControlObligatoryBothPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos obligatorios: {0}.
        /// </summary>
        public static string ConfigUserControlObligatoryField {
            get {
                return ResourceManager.GetString("ConfigUserControlObligatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione imagen para el perfil.
        /// </summary>
        public static string ConfigUserControlSelectImageToProfile {
            get {
                return ResourceManager.GetString("ConfigUserControlSelectImageToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Películas.
        /// </summary>
        public static string ConfigWindowFilmHeader {
            get {
                return ResourceManager.GetString("ConfigWindowFilmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string ConfigWindowSerieHeader {
            get {
                return ResourceManager.GetString("ConfigWindowSerieHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string ConfigWindowUserHeader {
            get {
                return ResourceManager.GetString("ConfigWindowUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario actualizado con éxito..
        /// </summary>
        public static string cUserUpdateSuccessfully {
            get {
                return ResourceManager.GetString("cUserUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEPLEX.
        /// </summary>
        public static string lblApplicationTitle {
            get {
                return ResourceManager.GetString("lblApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejores.
        /// </summary>
        public static string lblBest {
            get {
                return ResourceManager.GetString("lblBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual:.
        /// </summary>
        public static string lblCurrentPasswordLbl {
            get {
                return ResourceManager.GetString("lblCurrentPasswordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración.
        /// </summary>
        public static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración:.
        /// </summary>
        public static string lblDurationLbl {
            get {
                return ResourceManager.GetString("lblDurationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string lblEmailLbl {
            get {
                return ResourceManager.GetString("lblEmailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información episodios.
        /// </summary>
        public static string lblEpisodesInfoHeader {
            get {
                return ResourceManager.GetString("lblEpisodesInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Películas.
        /// </summary>
        public static string lblFilms {
            get {
                return ResourceManager.GetString("lblFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Has olvidado tu contraseña?.
        /// </summary>
        public static string lblForgottenPassword {
            get {
                return ResourceManager.GetString("lblForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género 01:.
        /// </summary>
        public static string lblGenre01Lbl {
            get {
                return ResourceManager.GetString("lblGenre01Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género 02:.
        /// </summary>
        public static string lblGenre02Lbl {
            get {
                return ResourceManager.GetString("lblGenre02Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimas.
        /// </summary>
        public static string lblLast {
            get {
                return ResourceManager.GetString("lblLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string lblNameLbl {
            get {
                return ResourceManager.GetString("lblNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña nueva:.
        /// </summary>
        public static string lblNewPasswordLbl {
            get {
                return ResourceManager.GetString("lblNewPasswordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apodo:.
        /// </summary>
        public static string lblNickNameLbl {
            get {
                return ResourceManager.GetString("lblNickNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota:.
        /// </summary>
        public static string lblNoteLbl {
            get {
                return ResourceManager.GetString("lblNoteLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string lblPasswordLbl {
            get {
                return ResourceManager.GetString("lblPasswordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos:.
        /// </summary>
        public static string lblPermissionsLbl {
            get {
                return ResourceManager.GetString("lblPermissionsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha estreno:.
        /// </summary>
        public static string lblPremiereDateLbl {
            get {
                return ResourceManager.GetString("lblPremiereDateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string lblSeries {
            get {
                return ResourceManager.GetString("lblSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad.
        /// </summary>
        public static string lblSpeed {
            get {
                return ResourceManager.GetString("lblSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinópsis.
        /// </summary>
        public static string lblSynopsis {
            get {
                return ResourceManager.GetString("lblSynopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinopsis:.
        /// </summary>
        public static string lblSynopsisLbl {
            get {
                return ResourceManager.GetString("lblSynopsisLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título:.
        /// </summary>
        public static string lblTitleLbl {
            get {
                return ResourceManager.GetString("lblTitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIG.
        /// </summary>
        public static string LblUpperConfig {
            get {
                return ResourceManager.GetString("LblUpperConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PELIS.
        /// </summary>
        public static string LblUpperFilms {
            get {
                return ResourceManager.GetString("LblUpperFilms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSCAR.
        /// </summary>
        public static string LblUpperSearch {
            get {
                return ResourceManager.GetString("LblUpperSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIES.
        /// </summary>
        public static string LblUpperSeries {
            get {
                return ResourceManager.GetString("LblUpperSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url trailer.
        /// </summary>
        public static string lblUrl {
            get {
                return ResourceManager.GetString("lblUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url trailer:.
        /// </summary>
        public static string lblUrlLbl {
            get {
                return ResourceManager.GetString("lblUrlLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string lblUserLbl {
            get {
                return ResourceManager.GetString("lblUserLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumen.
        /// </summary>
        public static string lblVolume {
            get {
                return ResourceManager.GetString("lblVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string lblWarning {
            get {
                return ResourceManager.GetString("lblWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se envio el correo correctamente..
        /// </summary>
        public static string loggingWindowEmailSentError {
            get {
                return ResourceManager.GetString("loggingWindowEmailSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En unos segundos le llegará a su correo la nueva contraseña..
        /// </summary>
        public static string loggingWindowEmailSentSuccessful {
            get {
                return ResourceManager.GetString("loggingWindowEmailSentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y Contraseña no validos.
        ///Intentos : {0}/{1}..
        /// </summary>
        public static string LoggingWindowUserAndPasswordNotValid {
            get {
                return ResourceManager.GetString("LoggingWindowUserAndPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario introducido no existe..
        /// </summary>
        public static string loggingWindowUserNotExits {
            get {
                return ResourceManager.GetString("loggingWindowUserNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea reanudar la reproducción?.
        /// </summary>
        public static string MultimediaPlayerWindowResumeTime {
            get {
                return ResourceManager.GetString("MultimediaPlayerWindowResumeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar por:.
        /// </summary>
        public static string MultimediaSearchWindowLblSortBy {
            get {
                return ResourceManager.GetString("MultimediaSearchWindowLblSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        public static string MultimediaSearchWindowLblSortByNote {
            get {
                return ResourceManager.GetString("MultimediaSearchWindowLblSortByNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de estreno.
        /// </summary>
        public static string MultimediaSearchWindowLblSortByPremiereDate {
            get {
                return ResourceManager.GetString("MultimediaSearchWindowLblSortByPremiereDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string MultimediaSearchWindowLblSortByTitle {
            get {
                return ResourceManager.GetString("MultimediaSearchWindowLblSortByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando servicio....
        /// </summary>
        public static string splashWindowCheckingService {
            get {
                return ResourceManager.GetString("splashWindowCheckingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Al intentar actualizar los datos de la BD.
        /// </summary>
        public static string splashWindowErrorCheckUpdateData {
            get {
                return ResourceManager.GetString("splashWindowErrorCheckUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Carga completa! Pulse &apos;Enter&apos; para continuar..
        /// </summary>
        public static string splashWindowLoadCompleted {
            get {
                return ResourceManager.GetString("splashWindowLoadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando....
        /// </summary>
        public static string splashWindowLoading {
            get {
                return ResourceManager.GetString("splashWindowLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿El servicio no está vivo, vuelva a intentarlo?.
        /// </summary>
        public static string splashWindowServiceIsNotAlive {
            get {
                return ResourceManager.GetString("splashWindowServiceIsNotAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizando datos....
        /// </summary>
        public static string splashWindowUpdatingData {
            get {
                return ResourceManager.GetString("splashWindowUpdatingData", resourceCulture);
            }
        }
    }
}
